### ISSUE TITLE
clr-installer: 2.3.1: "no such file or directory" error when mounting rootfs, so unable to install Clear Linux from live-server image

### ISSUE THREAD

**Issue by thac0** [clearlinux/clr-installer#588] opened 2019-10-16 20:48 UTC
**Describe the bug**
While attempting to install 31310 from the live-server image from the console, I am not able to install Clear Linux because clr-installer errors out with a "no such file or directory" when attempting to mount the rootfs.

**To Reproduce**
1. Boot live-server image
2. As root, run "clr-installer"
3. Attempt a destructive installation on an NVME target (also reproducible if attempting to install from a --config YAML)
4. Begin installation
5. See error when clr-installer attempts to mount rootfs

**Expected behavior**
Clear Linux installs normally, from TUI interface or from a --config YAML.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31310
 - Installer Version 2.3.1
 - Platform: Dell XPS 13 9380

**Additional context**
N/A

**Comment by thac0** [comment] 2019-10-16 20:56
Snippet from pre-install-clr-installer.yaml:
```
targetMedia:
- name: nvme0n1
  size: "0"
  ro: "false"
  rm: "false"
  type: disk
  children:
  - name: nvme0n1p1
    fstype: vfat
    mountpoint: /boot
    label: boot
    size: "524288000"
    ro: "false"
    rm: "false"
    type: part
  - name: nvme0n1p2
    fstype: swap
    label: swap
    size: "8589934592"
    ro: "false"
    rm: "false"
    type: part
  - name: nvme0n1p3
    fstype: xfs
    mountpoint: /
    label: root
    size: "0"
    ro: "false"
    rm: "false"
    type: part
```

Snippet from clr-installer.log:
```
[snip]
2019/10/16 15:52:41 [INF] Mounting: /
2019/10/16 15:52:41 [DBG] telem-record-gen [snip]
mount /dev/nvme0n1p3 /tmp/install-822812093 xfs: no such file or directory

Error Trace:
storage.mountFs()
     storage/ops.go:965
storage.(*BlockDevice).Mount()
     storage/ops.go:178
[snip]
```

**Comment by mdhorn** [comment] 2019-10-16 20:58
@thac0 Is this consistently failing or intermittent?
I have seen this recently testing the tip on master on the latest release of Clear Linux OS, but only noticed it in QEMU.
There is something that changed in the OS in the past few days creating this instability.
Since the problem is in a native golang call, I'll first be trying creating a new build using the previous release of golang - we bumped from 1.13 to 1.13.1 this week.

**Comment by thac0** [comment] 2019-10-16 21:07
@mdhorn - Consistent. I poked around the clr-installer go code to see if there was something obvious, and nothing jumped at me, hence the filing.

**Comment by mdhorn** [comment] 2019-10-16 21:23
Could I get you to try an older release of Clear Linux OS, 
https://download.clearlinux.org/releases/31290/clear/clear-31290-live-server.iso

**Comment by thac0** [comment] 2019-10-16 21:30
@mdhorn - No issue when I roll back to 31290.

**Comment by mdhorn** [comment] 2019-10-16 21:44
@thac0 If you are willing, it would be super helpful to know if 31300 works
https://download.clearlinux.org/releases/31300/clear/clear-31300-live-server.iso
or if I can borrow your system for a few.  My QEMU failures aren't appearing for me in 31300, but are intermittent in 31310.

**Comment by thac0** [comment] 2019-10-16 21:55
@mdhorn - 31300 fails, same as 31310

**Comment by mdhorn** [comment] 2019-10-16 22:52
> @mdhorn - 31300 fails, same as 31310

Thank you for the information; it increases the scope of change but very useful.

**Comment by blsz** [comment] 2019-10-17 06:49
I had similar errors when trying to install from clear-31310-live-desktop to an xfs root on an Intel NUC8i7HVK.   Rolling back to 31290 worked.     I did not save the install logs.

**Comment by mdhorn** [comment] 2019-10-17 14:32
> I had similar errors when trying to install from clear-31310-live-desktop to an xfs root on an Intel NUC8i7HVK. Rolling back to 31290 worked. I did not save the install logs.

@blsz thank you for the report. 

We’ve requested the default Desktop and Server ISO images be frozen at 31290 while this is under investigation.

**Comment by mdhorn** [comment] 2019-10-23 18:45
The problem was due to a new release of parted in Clear Linux OS. It jumped from 3.2 to 3.3 and this is causing the issue. 
We are adding a check to help catch this and we will ensure the bug is fixed before moving to a new parted release.

The OS has reverted to 3.2 and the problem is resolved in the ISO images in release 31370 and greater.

**Closed by mdhorn** 2019-10-23 18:45 UTC
Labels: high priority, to be investigated

**Comment by blackthorne** [comment] 2020-06-17 23:58
I'm having the same problem with the Server v33390 .

**Comment by blackthorne** [comment] 2020-06-18 10:21
follow up: I was able to get away with a previous release. I don't know what is the exact version in which this problem was introduced but I was able to narrow it down to somewhere in between v33000 (fails) and v32950 (works).

**Comment by ericcurtin** [comment] 2022-05-27 13:02
Getting the same using clear-36010-live-server.iso

![image](https://user-images.githubusercontent.com/1694275/170704403-7ab0373b-09fd-4c59-b2b6-d88cba8c66b5.png)

**Comment by ericcurtin** [comment] 2022-05-27 13:06
Re-ran installation seemed to be fine, seemed intermittent as suggested.

**Comment by ericcurtin** [comment] 2022-06-01 10:18
It happens more often than not for me though struggling today

**Comment by ericcurtin** [comment] 2022-06-01 10:23
`while ! clr-installer -c /root/pre-install-clr-installer.yaml; do true; done` might be a hacky workaround for this if it fails first time
