### ISSUE TITLE
LVM

### ISSUE THREAD

**Issue by manish3kumar** [clearlinux/clr-installer#220] opened 2019-02-14 11:05 UTC
We have purchased Buchanan pass H2312XXLR3 as server. It has 2 * 2TB hard drive

While doing the installation, we want to club both hard disk to be considered for partition together
how is that possible? Is LVM supports it? If yes, then please let me know the steps.

CL version: 27780

**Comment by manish3kumar** [comment] 2019-02-14 11:06
Is LVM on root file system possible while post installation?

**Comment by mdhorn** [comment] 2019-02-15 00:27
@manish3kumar LVM is not currently supported by the Clear Linux OS Installer.
We have been tracking an Issue for this for a while, so this is a duplicate of #8

**Comment by mdhorn** [comment] 2019-02-15 21:43
Until we can add support to the boot sequence to understand LVM, even manually migrating the root file system to an LVM partition won't work as you won't be able to mount root '/' on boot.

You can use LVM for any other file systems like your /home or data partitions.

Please watch Issue #8 for future updates on LVM support.

**Closed by mdhorn** 2019-02-15 21:43 UTC
Labels: duplicate
