### ISSUE TITLE
Color scheme is really hard on the eyes.  Would prefer more neutral colors.

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#208] opened 2019-02-01 19:40 UTC
IMHO, the current color scheme is really hard to use.  It's hard to read the blue text inside an aquamarine text field (see attached for example).  Can we use more neutral colors or shades of gray?  
![img_2278](https://user-images.githubusercontent.com/29260389/52145543-1c73d500-2616-11e9-9c78-33bcb1d5546b.jpg)

**Comment by mdhorn** [comment] 2020-01-08 01:43
Closing as duplicate of #217 which ha well-defined reason for a different theme

**Closed by mdhorn** 2020-01-08 01:43 UTC
Labels: TUI, duplicate, enhancement
