### ISSUE TITLE
clr-installer is stuck with lvm group existing on system

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/clr-installer#627] opened 2019-12-14 17:32 UTC
Hi Clear Linux team,

I tried to do a new installation of the CL operating system.
But we have an older operating system on disk with lvm.
I chose a destructive installation.
But this does not work.
By simple debugging, the lvm group is still active in CL.
Can this problem be repaired?
Maybe the lvm group should be stopped and removed by clr-installer.

Thank you CL team.

cat /etc/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=31890
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

[clr-installer.log](https://github.com/clearlinux/clr-installer/files/3964110/clr-installer.log)
[fdisk.txt](https://github.com/clearlinux/clr-installer/files/3964111/fdisk.txt)
[journalctl.log](https://github.com/clearlinux/clr-installer/files/3964112/journalctl.log)
[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/clr-installer/files/3964113/pre-install-clr-installer.yaml.txt)

**Comment by mdhorn** [comment] 2019-12-15 21:35
This is a duplicate of https://github.com/clearlinux/clr-installer/issues/623

**Closed by mdhorn** 2019-12-15 21:35 UTC
Labels: duplicate
