### ISSUE TITLE
Allow keyboard config to be passed through to install target

### ISSUE THREAD

**Issue by nesiusra** [clearlinux/clr-installer#630] opened 2019-12-30 17:56 UTC
Please update the installer program for keyboard selection

Please allow the installer person to setup up his keyboard now,
during installation, and not after a boot.

My keyboard does not have the US standard version layout.
My default password has characters not defined on the USA English layout.

Fortunately, to complete the installation I created a password called  xyz123xyz
and after the first boot I did a  setup for the appropriate keyboard
and default language, I then redo the password to include
those characters not available on the USA keyboard layout.

**To Reproduce**
Steps to reproduce the behavior: As above

**Expected behavior**

Keyboard configured in installer is usable in install target on first boot. 

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
Possibly a feature request, though the user experience feels "bug-like."

**Comment by mdhorn** [comment] 2020-02-21 18:39
This looks like a duplicate of #492

**Comment by mdhorn** [comment] 2020-03-10 22:06
Closing as duplicate of #492

**Closed by mdhorn** 2020-03-10 22:06 UTC
Labels: bug_triage, duplicate
