### ISSUE TITLE
Clear Linux installer (clr-installer) TUI does not show up on serial console

### ISSUE THREAD

**Issue by sachinmokashi** [clearlinux/clr-installer#475] opened 2019-07-18 08:27 UTC
**Describe the bug**
After logging in the booted ISO image with the clrlinux user, running `sudo -E clr-installer` will return an empty screen.

**To Reproduce**
Download Clear Linux ISO image:
$ export IMG_NAME=clear-30070-live-desktop.iso
$ curl http://linux-ftp.jf.intel.com/pub/mirrors/clearlinux/image/${IMG_NAME}.xz | xzcat > /tmp/${IMG_NAME}
create a QEMU 20G virtual disk:
$ qemu-img create -f qcow2 image.qcow2 20G
Download BIOS file for QEMU:
$ curl -o /tmp/OVMF.fd http://linux-ftp.jf.intel.com/pub/mirrors/clearlinux/image/OVMF.fd
Boot the ISO image with a virtual machine instance:
$ export VMN=${VMN:=1} 
$ qemu-system-x86_64 -bios /tmp/OVMF.fd --enable-kvm -m 2048 -hda image.qcow2 -smp sockets=1,cpus=4,cores=2 -cpu host -vga none -nographic -netdev user,id=mynet0,hostfwd=tcp::${VMN}0022-:22,hostfwd=tcp::${VMN}2375-:2375 -device virtio-net-pci,netdev=mynet0 -device virtio-rng-pci -cdrom /tmp/${IMG_NAME}
Log in with the user “clrlinux” (no password is needed).
Start the installer:
$ sudo -E clr-installer

**Expected behavior**
Clear Linux installer should show a TUI-based installation wizard.

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS Version: [swupd info]
30070

 - Installer Version [clr-installer -v]
2.0.7

 - Platform: [hardware infomation]
H/W: QEMU virtualised environment

**Comment by mdhorn** [comment] 2019-07-18 17:59
Please try running `sudo -E clr-installer-tui` or `sudo -E clr-installer --tui`

You are loading the Desktop image, and there will be graphical desktop running, my guess is you are launching the graphical version on the desktop which is why you doesn't see the text-based version on your terminal.

**Comment by sachinmokashi** [comment] 2019-08-09 02:40
Hi @mdhorn : Tried the `sudo -E clr-installer --tui` but it still doesn't seem to work on QEMU virtualized environment. However I am able to see the TUI when I directly boot the desktop image on any NUC.

**Comment by mdhorn** [comment] 2019-08-09 17:59
@sachinmokashi  This appears to be a problem with terminal settings.

After logging in as `clrlinux`, run the command `reset`, then `sudo clr-installer --tui`
or
After logging in as `clrlinux`, run the command `stty rows 24 columns 80`, then `sudo clr-installer --tui`

If you are only planning to use the TUI installer, you might want to consider downloading the live-server image which does not have the graphical desktop which makes the image much smaller. Note that the sever image won't have the `reset` command so you'll have to set the rows and column instead.

This use to work, but something must have changed which doesn't properly set the size of the terminal; the question is when and where.

**Comment by sachinmokashi** [comment] 2019-08-13 02:23
@mdhorn I am glad to report that both the commands work! It was indeed the terminal settings issue.

Thanks for the resolution! I will proceed to close this issue.

**Comment by mdhorn** [comment] 2019-08-13 17:46
@sachinmokashi I'm going to re-open this as we have a workaround, but not a solution as to why we need to start setting the rows and columns.
I want to try and track down what changed in the OS to cause this at some point.

**Comment by sachinmokashi** [comment] 2019-08-14 07:33
@mdhorn Much appreciated!

**Comment by mdhorn** [comment] 2019-10-10 04:23
Found that the problem with the terminal not getting the correct rows and columns started after Clear Linux OS release 29820 (last working version) and first appeared in 29850 (the first external release).
The changes are documented here:
https://download.clearlinux.org/releases/29850/clear/RELEASENOTES-29820-to-29850

**Comment by mdhorn** [comment] 2019-10-10 04:25
To clarify, the problem is in the OS release, not the installer, but still not clear what specific changed caused the problem.

**Comment by mdhorn** [comment] 2019-10-12 00:06
### Workaround
`setterm --resize`
This binary is already in the server image as well.

**Comment by sachinmokashi** [comment] 2019-10-15 02:23
@mdhorn I did see your patch `[Clr-dev] [PATCH filesystem] Ensure interactive terminal has rows and columns` Hopefully that should be able to fix the problem!

**Comment by mdhorn** [comment] 2019-11-14 00:06
Closing this now that the OS has been patched to ensure that the terminal size is properly set.

**Closed by mdhorn** 2019-11-14 00:06 UTC
Labels: UX, bug_triage
