### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by IgorDouven** [clearlinux/clr-installer#440] opened 2019-06-14 14:02 UTC
Made another attempt to install CL on my main machine. The live desktop environment (29820) booted into a black screen. Then used the live server (also 29820), which first gave me some error messages (nouveau secboot: error during falcon reset, -110, and two more also related to the graphics driver -- I suppose that explains the black screen of the live desktop?), but then did let me start the installer. However, that couldn't find any usable media. I had the same problem some months ago and then was told it was related to a problem with my ssd, a Samsung 970 Pro M.2. I had hoped that would have been solved in the meantime, but in any case, I thought I let the team know that the problem still exists.

**Comment by miguelinux** [comment] 2019-06-14 16:33
Can you help us by describing your HW?

**Comment by IgorDouven** [comment] 2019-06-14 16:45
Yes, of course: AMD RyzenThreadripper 2920X processor; ASUS Prime X399-A
motherboard; Corsair Vengeance LPX Black 32GB memory; and the Samsung ssd I
mentioned.

Op vr 14 jun. 2019 om 18:33 schreef Miguel Bernal Marin <
notifications@github.com>:

**Comment by bwarden** [comment] 2019-08-14 20:43
Likely related to https://github.com/clearlinux/distribution/issues/392

**Comment by RyanSmithOnline** [comment] 2019-08-22 14:52
I have the same hard drive. NVME, Samsung 970 Pro. The installer does not find my drive.

**Comment by bwarden** [comment] 2019-08-22 15:42
> I have the same hard drive. NVME, Samsung 970 Pro. The installer does not find my drive.

Motherboard brand/model and BIOS/firmware version?

**Comment by RyanSmithOnline** [comment] 2019-08-22 15:44
Hey @bwarden so it's the ROG Crosshair VII Hero, currently running BIOS version 2701 but the problem was the same for at least the last 5 bios versions.

**Comment by bwarden** [comment] 2019-08-23 16:55
Can you try adding "pcie_aspm=off" to the kernel command line?

**Comment by RyanSmithOnline** [comment] 2019-08-23 17:45
@bwarden thanks that does it, the drive shows.

Let me know if you want me to test to help narrow down the issue.

**Comment by mdhorn** [comment] 2019-09-16 21:06
@miguelinux @bwarden Do we need to make a kernel change based on this?  Or a change to the kernel parameters used for the installer images?

**Comment by mdhorn** [comment] 2019-09-16 21:25
Moving this to the Distribution has any change will likely be to the kernel.

**Comment by mdhorn** [comment] 2019-09-16 21:26
Actually, this is a duplicate of https://github.com/clearlinux/distribution/issues/392
Closing as duplicate.

If you are not already following https://github.com/clearlinux/distribution/issues/392 please do so for further updates.

**Closed by mdhorn** 2019-09-16 21:26 UTC
Labels: bug_triage, question, waiting on input
