### ISSUE TITLE
can't use the same installer image twice with non us keyboard layout

### ISSUE THREAD

**Issue by bryteise** [clearlinux/clr-installer#264] opened 2019-03-11 23:32 UTC
**Describe the bug**
From irc:

<Superthug> meh i found a bug in last to installer images
<Superthug> when doing a first install it works all good
<Superthug> but using same usb stick doing another install it crashes when you choose another keyboard layout than default us
<Superthug> does this every time
<Superthug> image have to be rewritten to stick then it works to install once

**Comment by mdhorn** [comment] 2019-03-11 23:38
@bryteise Were you able to reproduce this?
What keyboard was selected?

I want more data from the people experiencing the problem I think rather any someone seeing it on IRC and opening an Issue.

**Comment by bryteise** [comment] 2019-03-11 23:39
Unfortunately the person didn't have anybody respond to them and hopped offline so this all we have to go on.

**Comment by mdhorn** [comment] 2019-05-17 23:59
Closing since we do not have access to the report and insufficient data to reproduced what was reported.

**Closed by mdhorn** 2019-05-17 23:59 UTC
Labels: sighting
